apiVersion: v1
kind: Secret
metadata:
  name: {{ include "salty-spitoon.fullname" . }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.s3.secret_access_key | b64enc | quote }}
  JWT_SIGNATURE_KEY: {{ .Values.auth.jwt_signature_key | b64enc | quote }}
