apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weenie-hut.fullname" . }}
data:
  PORT: {{ .Values.app.port | quote }}
  APP_ENV: {{ .Values.app.env }}
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_DATABASE: {{ .Values.db.database | quote }}
  DB_USERNAME: {{ .Values.db.username | quote}}
  DB_SCHEMA: {{ .Values.db.schema }}
  S3_ACCESS_KEY_ID: {{ .Values.s3.access_key_id | quote}}
  S3_ENDPOINT: {{ .Values.s3.endpoint | quote }}
  S3_BUCKET: {{ .Values.s3.bucket | quote }}
  OTLP_ENDPOINT: {{ .Values.observability.otlp_endpoint | quote}}
  MAX_CONCURRENT_COMPRESS: {{ .Values.image_compression.max_concurrent | quote }}
  IMAGE_COMPRESSION_QUALITY: {{ .Values.image_compression.quality | quote }}
